import { askJarvis } from './ai.service.js';

export async function generateProjectFiles(requirement: string) {
  const prompt = `Generate a compact production-ready web project for this requirement: ${requirement}.
Return only JSON with keys name, stack, files. files must be an array of {path, content}. Include package.json, README.md, app/page.tsx or index.html, and styling.`;
  const answer = await askJarvis([{ role: 'user', content: prompt }]);
  try {
    const parsed = JSON.parse(answer.replace(/^```json|```$/g, '').trim()) as { name?: string; stack?: string[]; files?: Array<{ path: string; content: string }> };
    if (parsed.files?.length) return parsed;
  } catch {
    // Fall back to deterministic starter below when the model returns prose or no provider is configured.
  }
  const safeName = requirement.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50) || 'jarvis-project';
  return {
    name: safeName,
    stack: ['Next.js', 'React', 'Tailwind CSS'],
    files: [
      { path: 'package.json', content: JSON.stringify({ scripts: { dev: 'next dev', build: 'next build', start: 'next start' }, dependencies: { next: 'latest', react: 'latest', 'react-dom': 'latest' }, devDependencies: { tailwindcss: 'latest', typescript: 'latest' } }, null, 2) },
      { path: 'README.md', content: `# ${safeName}\n\nGenerated by JARVIS for: ${requirement}\n` },
      { path: 'app/page.tsx', content: `export default function Page() {\n  return <main className="min-h-screen bg-slate-950 text-white"><section className="mx-auto max-w-5xl px-6 py-24"><h1 className="text-5xl font-black">${requirement}</h1><p className="mt-6 text-xl text-cyan-200">Production-ready starter generated by JARVIS.</p></section></main>;\n}\n` }
    ]
  };
}
